name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # enable manual execution

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: mkdir ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --target all -j 14 --

    - name: Test
      run: ./${{github.workspace}}/build/test/tests
